// Code generated by graphql-codegen. DO NOTT EDIT.

import * as Types from "../graphqlTypes";

export type PostSummaryFragment = {
  __typename?: "Post";
  title: string;
  body: string;
  user: { __typename?: "User"; username: string; thumbnailUrl?: string | null };
} & { " $fragmentName": "PostSummaryFragment" };

export type GetPostSummaryQueryVariables = Types.Exact<{
  postId: Types.Scalars["String"];
}>;

export type GetPostSummaryQuery = {
  __typename?: "Query";
  postById: { __typename?: "Post"; id: string } & {
    " $fragmentRefs": { PostSummaryFragment: PostSummaryFragment };
  };
};
