// Code generated by graphql-codegen. DO NOTT EDIT.

import * as Types from "../graphqlTypes";

export type UserHeaderFragment = {
  __typename?: "User";
  username: string;
  avatarUrl?: string | null;
} & { " $fragmentName": "UserHeaderFragment" };

export type GetUserHeaderQueryVariables = Types.Exact<{
  userId: Types.Scalars["String"];
}>;

export type GetUserHeaderQuery = {
  __typename?: "Query";
  userById: { __typename?: "User"; id: string } & {
    " $fragmentRefs": { UserHeaderFragment: UserHeaderFragment };
  };
};
