// Code generated by graphql-codegen. DO NOTT EDIT.

import * as Types from "../graphqlTypes";

export type PostHeaderUserFragment = {
  __typename?: "User";
  username: string;
  avatarUrl?: string | null;
} & { " $fragmentName": "PostHeaderUserFragment" };

export type PostHeaderFragment = {
  __typename?: "Post";
  title: string;
  author: { __typename?: "User" } & {
    " $fragmentRefs": { PostHeaderUserFragment: PostHeaderUserFragment };
  };
} & { " $fragmentName": "PostHeaderFragment" };

export type GetPostHeaderQueryVariables = Types.Exact<{
  postId: Types.Scalars["String"];
}>;

export type GetPostHeaderQuery = {
  __typename?: "Query";
  postById: {
    __typename?: "Post";
    id: string;
    author: { __typename?: "User"; id: string };
  } & { " $fragmentRefs": { PostHeaderFragment: PostHeaderFragment } };
};
