// Code generated by graphql-codegen. DO NOTT EDIT.

import * as Types from "../graphqlTypes";

export type PostListItemFragment = {
  __typename?: "Post";
  title: string;
  author: {
    __typename?: "User";
    id: string;
    avatarUrl?: string | null;
    username: string;
  };
} & { " $fragmentName": "PostListItemFragment" };

export type ListPostsQueryVariables = Types.Exact<{
  userId: Types.Scalars["String"];
}>;

export type ListPostsQuery = {
  __typename?: "Query";
  postsByUserId: Array<
    { __typename?: "Post"; id: string } & {
      " $fragmentRefs": { PostListItemFragment: PostListItemFragment };
    }
  >;
};
