// Code generated by graphql-codegen. DO NOTT EDIT.

import * as Types from "../graphqlTypes";

export type PostWithAuthorFragment = {
  __typename?: "Post";
  title: string;
  author: { __typename?: "User"; username: string };
};

export type GetPostWithAuthorQueryVariables = Types.Exact<{
  postId: Types.Scalars["String"];
}>;

export type GetPostWithAuthorQuery = {
  __typename?: "Query";
  postById: { __typename?: "Post"; id: string } & PostWithAuthorFragment;
};
