// Code generated by graphql-codegen. DO NOTT EDIT.

import * as Types from "../graphqlTypes";

export type PostUserAvatarFragment = {
  __typename?: "Post";
  author: { __typename?: "User"; avatarUrl?: string | null };
};

export type PostDetailHeaderFragment = {
  __typename?: "Post";
  title: string;
} & PostUserAvatarFragment;

export type PostDetailFragment = {
  __typename?: "Post";
  title: string;
  body: string;
  author: { __typename?: "User"; username: string };
} & PostUserAvatarFragment;

export type GetPostDetailQueryVariables = Types.Exact<{
  postId: Types.Scalars["String"];
}>;

export type GetPostDetailQuery = {
  __typename?: "Query";
  postById: { __typename?: "Post"; id: string } & PostDetailFragment &
    PostDetailHeaderFragment;
};
